trying actions from modules

diff --git a/.github/actions/get-shards/action.yml b/.github/actions/get-shards/action.yml
--- a/.github/actions/get-shards/action.yml
+++ b/.github/actions/get-shards/action.yml
@@ -7,6 +7,9 @@ inputs:
   max_shards:
     description: "Maximum number of shards allowed"
     required: true
+  paths:
+    description: "Component paths to test"
+    required: false
 outputs:
   shard:
     description: "Array of shard numbers"
@@ -14,7 +17,6 @@ outputs:
   total_shards:
     description: "Total number of shards"
     value: ${{ steps.shards.outputs.total_shards }}
-
 runs:
   using: "composite"
   steps:
@@ -23,13 +25,21 @@ runs:
       with:
         version: ${{ env.NFT_VER }}
         install-pdiff: true
-
     - name: Get number of shards
       id: shards
       shell: bash
       run: |
-        # Run nf-test to get the number of related tests
-        nftest_output=$(nf-test test --dry-run --changed-since HEAD^ --filter pipeline --tag ${{ inputs.tags }})
+        # Run nf-test with dynamic parameter
+        nftest_output=$(nf-test test \
+          --dry-run \
+          --profile +docker \
+          --filter pipeline \
+          --ci \
+          --changed-since HEAD^) || {
+            echo "nf-test command failed with exit code $?"
+            echo "Full output: $nftest_output"
+            exit 1
+        }
         echo "nf-test dry-run output: $nftest_output"
 
         # Default values for shard and total_shards
@@ -37,11 +47,11 @@ runs:
         total_shards=0
 
         # Check if there are related tests
-        if echo "$nftest_output" | grep -q 'Nothing to do'; then
+        if echo "$nftest_output" | grep -q 'No tests to execute'; then
           echo "No related tests found."
         else
           # Extract the number of related tests
-          number_of_shards=$(echo "$nftest_output" | sed -n 's|.*Found \([0-9]*\) related test.*|\1|p')
+          number_of_shards=$(echo "$nftest_output" | sed -n 's|.*Executed \([0-9]*\) tests.*|\1|p')
           if [[ -n "$number_of_shards" && "$number_of_shards" -gt 0 ]]; then
             shards_to_run=$(( $number_of_shards < ${{ inputs.max_shards }} ? $number_of_shards : ${{ inputs.max_shards }} ))
             shard=$(seq 1 "$shards_to_run" | jq -R . | jq -c -s .)
