Better summary

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -116,9 +116,11 @@ jobs:
       - name: Disk space cleanup
         uses: jlumbroso/free-disk-space@v1.3.1
 
-      - id: print-test
+      - name: Start summary
+        id: print-test
         run: |
-          echo "### Test summary :rocket:" >> $GITHUB_STEP_SUMMARY
+          echo "### nf-test tests summary :rocket:" >> $GITHUB_STEP_SUMMARY
+          echo "This shard contains the following tests:" >> $GITHUB_STEP_SUMMARY
           nf-test test \
             --ci \
             --dryRun \
@@ -130,24 +132,36 @@ jobs:
             --filter ${{ matrix.filter }} \
             | grep PASSED | cut -d "'" -f 2 | sort -u >> $GITHUB_STEP_SUMMARY
 
-      # - name: "Run tests | ${{ matrix.filter }}_${{ matrix.profile }} | ${{ matrix.shard }}/5"
-      #   run: |
-      #     nf-test test \
-      #         --ci \
-      #         --debug \
-      #         --verbose \
-      #         --junitxml="TEST-${{ matrix.filter }}_${{ matrix.profile }}_${{ matrix.shard }}.xml" \
-      #         --shard ${{ matrix.shard }}/5 \
-      #         --changed-since HEAD^ \
-      #         --follow-dependencies \
-      #         --profile "+${{ matrix.profile }}" \
-      #         --filter ${{ matrix.filter }}
+      - name: "Run tests | ${{ matrix.filter }}_${{ matrix.profile }} | ${{ matrix.shard }}/5"
+        run: |
+          nf-test test \
+              --ci \
+              --debug \
+              --verbose \
+              --junitxml="TEST-${{ matrix.filter }}_${{ matrix.profile }}_${{ matrix.shard }}.xml" \
+              --shard ${{ matrix.shard }}/5 \
+              --changed-since HEAD^ \
+              --follow-dependencies \
+              --profile "+${{ matrix.profile }}" \
+              --filter ${{ matrix.filter }}
 
-      # - name: Publish Test Report
-      #   uses: mikepenz/action-junit-report@v4
-      #   if: success() || failure() # always run even if the previous step fails
-      #   with:
-      #     report_paths: "TEST-*.xml"
+      - name: Print success in summary
+        if: success()
+        run: |
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "All tests successfull :rocket:" >> $GITHUB_STEP_SUMMARY
+
+      - name: Print failure in summary
+        if: failure()
+        run: |
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "Some tests failed :sadcold_sweat:" >> $GITHUB_STEP_SUMMARY
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "TEST-*.xml"
 
       - name: Clean up
         if: always()
